name: Run API Tests
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '16'

            - name: Install dependencies
              run: npm install

            - name: Create a reports directory
              run: mkdir -p reports

            - name: Run tests
              #run: npx mocha --reporter mochawesome --reporter-options reportDir=reports, reportFilename=report --exit
              run: |
                node ./node_modules/mocha/bin/mocha.js tests \
                --reporter mochawesome \
                --reporter-options reportDir=reports,reportFilename=report \
                --exit

            - name: Upload Test Report
              uses: actions/upload-artifact@v3
              with:
                    name: mocha-test-report
                    path: reports
